spring:
    datasource:
      url: "jdbc:mysql://localhost:3306/movies_db"
      username: "soul-rate-admin"
      password: "soul-rate-pass"
    jpa:
      database-platform: "org.hibernate.dialect.MySQL8Dialect"
      hibernate:
        ddl-auto: update
      generate-ddl: true