spring:
    datasource:
      url: "jdbc:mysql://soul-rate-admin:show-password@soul-rate-do-user-11419363-0.b.db.ondigitalocean.com:25060/feedback_reply_db?ssl-mode=REQUIRED"
      username: "soul-rate-admin"
      password: "soul-rate-pass"
    jpa:
      database-platform: "org.hibernate.dialect.MySQL8Dialect"
      hibernate:
        ddl-auto: update
      generate-ddl: true
      
server:
  port: 8001

# management:
#    port: 9000
