spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/user_db"
    username: "soul-rate-admin"
    password: "soul-rate-pass"
  jpa:
    database-plateform: "org-hibernate-dialect.MySQL8Dialect"
    hibernate:
      ddl-auto: update
    generate-ddl: true
    
server:
  port: "8002"
